const recommendations = {
    "tracks": [
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/2wUjUUtkb5lvLKcGKsKqsR"
              },
              "href": "https://api.spotify.com/v1/artists/2wUjUUtkb5lvLKcGKsKqsR",
              "id": "2wUjUUtkb5lvLKcGKsKqsR",
              "name": "Alessia Cara",
              "type": "artist",
              "uri": "spotify:artist:2wUjUUtkb5lvLKcGKsKqsR"
            }
          ],
          "available_markets": [
            "CA",
            "MX",
            "US"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/3rDbA12I5duZnlwakqDdZa"
          },
          "href": "https://api.spotify.com/v1/albums/3rDbA12I5duZnlwakqDdZa",
          "id": "3rDbA12I5duZnlwakqDdZa",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273e3ae597159d6c2541c4ee61b",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02e3ae597159d6c2541c4ee61b",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851e3ae597159d6c2541c4ee61b",
              "width": 64
            }
          ],
          "name": "Know-It-All (Deluxe)",
          "release_date": "2015-11-13",
          "release_date_precision": "day",
          "total_tracks": 13,
          "type": "album",
          "uri": "spotify:album:3rDbA12I5duZnlwakqDdZa"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/2wUjUUtkb5lvLKcGKsKqsR"
            },
            "href": "https://api.spotify.com/v1/artists/2wUjUUtkb5lvLKcGKsKqsR",
            "id": "2wUjUUtkb5lvLKcGKsKqsR",
            "name": "Alessia Cara",
            "type": "artist",
            "uri": "spotify:artist:2wUjUUtkb5lvLKcGKsKqsR"
          }
        ],
        "available_markets": [
          "CA",
          "MX",
          "US"
        ],
        "disc_number": 1,
        "duration_ms": 254506,
        "explicit": false,
        "external_ids": {
          "isrc": "USUM71506813"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/5NRl32BO29q8xtWFvOlHZE"
        },
        "href": "https://api.spotify.com/v1/tracks/5NRl32BO29q8xtWFvOlHZE",
        "id": "5NRl32BO29q8xtWFvOlHZE",
        "is_local": false,
        "name": "River Of Tears",
        "popularity": 62,
        "preview_url": null,
        "track_number": 12,
        "type": "track",
        "uri": "spotify:track:5NRl32BO29q8xtWFvOlHZE"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4NHQUGzhtTLFvgF5SZesLK"
              },
              "href": "https://api.spotify.com/v1/artists/4NHQUGzhtTLFvgF5SZesLK",
              "id": "4NHQUGzhtTLFvgF5SZesLK",
              "name": "Tove Lo",
              "type": "artist",
              "uri": "spotify:artist:4NHQUGzhtTLFvgF5SZesLK"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/5Z5O36p7BivXzkucc0PAfw"
          },
          "href": "https://api.spotify.com/v1/albums/5Z5O36p7BivXzkucc0PAfw",
          "id": "5Z5O36p7BivXzkucc0PAfw",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27370cd79659edf4d5fec0840b8",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0270cd79659edf4d5fec0840b8",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485170cd79659edf4d5fec0840b8",
              "width": 64
            }
          ],
          "name": "Queen Of The Clouds",
          "release_date": "2014-09-24",
          "release_date_precision": "day",
          "total_tracks": 18,
          "type": "album",
          "uri": "spotify:album:5Z5O36p7BivXzkucc0PAfw"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4NHQUGzhtTLFvgF5SZesLK"
            },
            "href": "https://api.spotify.com/v1/artists/4NHQUGzhtTLFvgF5SZesLK",
            "id": "4NHQUGzhtTLFvgF5SZesLK",
            "name": "Tove Lo",
            "type": "artist",
            "uri": "spotify:artist:4NHQUGzhtTLFvgF5SZesLK"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 228960,
        "explicit": false,
        "external_ids": {
          "isrc": "SEUM71401534"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3mfu1aiVjGwjkAzDHcKsQW"
        },
        "href": "https://api.spotify.com/v1/tracks/3mfu1aiVjGwjkAzDHcKsQW",
        "id": "3mfu1aiVjGwjkAzDHcKsQW",
        "is_local": false,
        "name": "Got Love",
        "popularity": 39,
        "preview_url": null,
        "track_number": 9,
        "type": "track",
        "uri": "spotify:track:3mfu1aiVjGwjkAzDHcKsQW"
      },
      {
        "album": {
          "album_type": "SINGLE",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/01pKrlgPJhm5dB4lneYAqS"
              },
              "href": "https://api.spotify.com/v1/artists/01pKrlgPJhm5dB4lneYAqS",
              "id": "01pKrlgPJhm5dB4lneYAqS",
              "name": "Sigma",
              "type": "artist",
              "uri": "spotify:artist:01pKrlgPJhm5dB4lneYAqS"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AZ",
            "BA",
            "BB",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BO",
            "BR",
            "BS",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GD",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HN",
            "HR",
            "HT",
            "HU",
            "IL",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KI",
            "KM",
            "KN",
            "KW",
            "KZ",
            "LB",
            "LC",
            "LI",
            "LR",
            "LS",
            "LT",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MR",
            "MT",
            "MU",
            "MW",
            "MX",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NO",
            "NR",
            "OM",
            "PA",
            "PE",
            "PG",
            "PL",
            "PS",
            "PT",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SI",
            "SK",
            "SL",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TJ",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7Kg4q4c8IP7oc0rtelBXBK"
          },
          "href": "https://api.spotify.com/v1/albums/7Kg4q4c8IP7oc0rtelBXBK",
          "id": "7Kg4q4c8IP7oc0rtelBXBK",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273254d9a590f345309e209b558",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02254d9a590f345309e209b558",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851254d9a590f345309e209b558",
              "width": 64
            }
          ],
          "name": "Nobody To Love",
          "release_date": "2014-01-01",
          "release_date_precision": "day",
          "total_tracks": 10,
          "type": "album",
          "uri": "spotify:album:7Kg4q4c8IP7oc0rtelBXBK"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/01pKrlgPJhm5dB4lneYAqS"
            },
            "href": "https://api.spotify.com/v1/artists/01pKrlgPJhm5dB4lneYAqS",
            "id": "01pKrlgPJhm5dB4lneYAqS",
            "name": "Sigma",
            "type": "artist",
            "uri": "spotify:artist:01pKrlgPJhm5dB4lneYAqS"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AZ",
          "BA",
          "BB",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BO",
          "BR",
          "BS",
          "BW",
          "BY",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HN",
          "HR",
          "HT",
          "HU",
          "IL",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KI",
          "KM",
          "KN",
          "KW",
          "KZ",
          "LB",
          "LC",
          "LI",
          "LR",
          "LS",
          "LT",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MR",
          "MT",
          "MU",
          "MW",
          "MX",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NO",
          "NR",
          "OM",
          "PA",
          "PE",
          "PG",
          "PL",
          "PS",
          "PT",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SI",
          "SK",
          "SL",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TJ",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 189720,
        "explicit": false,
        "external_ids": {
          "isrc": "GBSXS1400074"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/2jsmSLoX8y0h6k4YzDCFH1"
        },
        "href": "https://api.spotify.com/v1/tracks/2jsmSLoX8y0h6k4YzDCFH1",
        "id": "2jsmSLoX8y0h6k4YzDCFH1",
        "is_local": false,
        "name": "Nobody To Love - Radio Edit",
        "popularity": 65,
        "preview_url": null,
        "track_number": 1,
        "type": "track",
        "uri": "spotify:track:2jsmSLoX8y0h6k4YzDCFH1"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/4YrKBkKSVeqDamzBPWVnSJ"
              },
              "href": "https://api.spotify.com/v1/artists/4YrKBkKSVeqDamzBPWVnSJ",
              "id": "4YrKBkKSVeqDamzBPWVnSJ",
              "name": "Basement Jaxx",
              "type": "artist",
              "uri": "spotify:artist:4YrKBkKSVeqDamzBPWVnSJ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1fuDdObQ1ncWsOEUjKIQxv"
          },
          "href": "https://api.spotify.com/v1/albums/1fuDdObQ1ncWsOEUjKIQxv",
          "id": "1fuDdObQ1ncWsOEUjKIQxv",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273af0303d2f6c6283569718c21",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02af0303d2f6c6283569718c21",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851af0303d2f6c6283569718c21",
              "width": 64
            }
          ],
          "name": "Junto (Special Edition)",
          "release_date": "2014-08-25",
          "release_date_precision": "day",
          "total_tracks": 26,
          "type": "album",
          "uri": "spotify:album:1fuDdObQ1ncWsOEUjKIQxv"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/4YrKBkKSVeqDamzBPWVnSJ"
            },
            "href": "https://api.spotify.com/v1/artists/4YrKBkKSVeqDamzBPWVnSJ",
            "id": "4YrKBkKSVeqDamzBPWVnSJ",
            "name": "Basement Jaxx",
            "type": "artist",
            "uri": "spotify:artist:4YrKBkKSVeqDamzBPWVnSJ"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 263053,
        "explicit": false,
        "external_ids": {
          "isrc": "GBPVV1400877"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/42suZFjDtBbl9sESKm4oj2"
        },
        "href": "https://api.spotify.com/v1/tracks/42suZFjDtBbl9sESKm4oj2",
        "id": "42suZFjDtBbl9sESKm4oj2",
        "is_local": false,
        "name": "Never Say Never - Extended Mix",
        "popularity": 44,
        "preview_url": "https://p.scdn.co/mp3-preview/ee0ff03825bfd3867f612770e65ac7aa05ee7b58?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 4,
        "type": "track",
        "uri": "spotify:track:42suZFjDtBbl9sESKm4oj2"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0IF46mUS8NXjgHabxk2MCM"
              },
              "href": "https://api.spotify.com/v1/artists/0IF46mUS8NXjgHabxk2MCM",
              "id": "0IF46mUS8NXjgHabxk2MCM",
              "name": "Kelis",
              "type": "artist",
              "uri": "spotify:artist:0IF46mUS8NXjgHabxk2MCM"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/7rOLlR197BcHUxYOfvi1BC"
          },
          "href": "https://api.spotify.com/v1/albums/7rOLlR197BcHUxYOfvi1BC",
          "id": "7rOLlR197BcHUxYOfvi1BC",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27382d2a515619137718f165ecf",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0282d2a515619137718f165ecf",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485182d2a515619137718f165ecf",
              "width": 64
            }
          ],
          "name": "Food",
          "release_date": "2014-04-21",
          "release_date_precision": "day",
          "total_tracks": 13,
          "type": "album",
          "uri": "spotify:album:7rOLlR197BcHUxYOfvi1BC"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0IF46mUS8NXjgHabxk2MCM"
            },
            "href": "https://api.spotify.com/v1/artists/0IF46mUS8NXjgHabxk2MCM",
            "id": "0IF46mUS8NXjgHabxk2MCM",
            "name": "Kelis",
            "type": "artist",
            "uri": "spotify:artist:0IF46mUS8NXjgHabxk2MCM"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 193546,
        "explicit": false,
        "external_ids": {
          "isrc": "GBCFB1306800"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/3Rm8WZtaNoawwisPDqjw1E"
        },
        "href": "https://api.spotify.com/v1/tracks/3Rm8WZtaNoawwisPDqjw1E",
        "id": "3Rm8WZtaNoawwisPDqjw1E",
        "is_local": false,
        "name": "Rumble",
        "popularity": 32,
        "preview_url": "https://p.scdn.co/mp3-preview/02354d09a8619521e1c59dae68119a4780c47ac1?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 11,
        "type": "track",
        "uri": "spotify:track:3Rm8WZtaNoawwisPDqjw1E"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/64PJHZDQTPPVBCdwnv22Wz"
              },
              "href": "https://api.spotify.com/v1/artists/64PJHZDQTPPVBCdwnv22Wz",
              "id": "64PJHZDQTPPVBCdwnv22Wz",
              "name": "Josef Salvat",
              "type": "artist",
              "uri": "spotify:artist:64PJHZDQTPPVBCdwnv22Wz"
            }
          ],
          "available_markets": [
            "AD",
            "BE",
            "CA",
            "DZ",
            "FR",
            "LU",
            "MA",
            "MC",
            "TN"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/1excMWyBjh9UJqk2xYZ7o0"
          },
          "href": "https://api.spotify.com/v1/albums/1excMWyBjh9UJqk2xYZ7o0",
          "id": "1excMWyBjh9UJqk2xYZ7o0",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b2731e7b45787876216180d4f007",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e021e7b45787876216180d4f007",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d000048511e7b45787876216180d4f007",
              "width": 64
            }
          ],
          "name": "Night Swim",
          "release_date": "2015-10-23",
          "release_date_precision": "day",
          "total_tracks": 13,
          "type": "album",
          "uri": "spotify:album:1excMWyBjh9UJqk2xYZ7o0"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/64PJHZDQTPPVBCdwnv22Wz"
            },
            "href": "https://api.spotify.com/v1/artists/64PJHZDQTPPVBCdwnv22Wz",
            "id": "64PJHZDQTPPVBCdwnv22Wz",
            "name": "Josef Salvat",
            "type": "artist",
            "uri": "spotify:artist:64PJHZDQTPPVBCdwnv22Wz"
          }
        ],
        "available_markets": [
          "AD",
          "BE",
          "CA",
          "DZ",
          "FR",
          "LU",
          "MA",
          "MC",
          "TN"
        ],
        "disc_number": 1,
        "duration_ms": 247600,
        "explicit": false,
        "external_ids": {
          "isrc": "GBARL1401157"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/6Hki3HcbeU2c4T72lJjyZ5"
        },
        "href": "https://api.spotify.com/v1/tracks/6Hki3HcbeU2c4T72lJjyZ5",
        "id": "6Hki3HcbeU2c4T72lJjyZ5",
        "is_local": false,
        "name": "Diamonds",
        "popularity": 33,
        "preview_url": "https://p.scdn.co/mp3-preview/6523fc1b746ffe61d3386a9fc14242055d4f2797?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 12,
        "type": "track",
        "uri": "spotify:track:6Hki3HcbeU2c4T72lJjyZ5"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/0X2BH1fck6amBIoJhDVmmJ"
              },
              "href": "https://api.spotify.com/v1/artists/0X2BH1fck6amBIoJhDVmmJ",
              "id": "0X2BH1fck6amBIoJhDVmmJ",
              "name": "Ellie Goulding",
              "type": "artist",
              "uri": "spotify:artist:0X2BH1fck6amBIoJhDVmmJ"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/2Dw4fYqDQnxsgoXDdMbqh3"
          },
          "href": "https://api.spotify.com/v1/albums/2Dw4fYqDQnxsgoXDdMbqh3",
          "id": "2Dw4fYqDQnxsgoXDdMbqh3",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b27360a98c3be4daffefe9014c7e",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e0260a98c3be4daffefe9014c7e",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d0000485160a98c3be4daffefe9014c7e",
              "width": 64
            }
          ],
          "name": "Halcyon Days",
          "release_date": "2014-01-01",
          "release_date_precision": "day",
          "total_tracks": 22,
          "type": "album",
          "uri": "spotify:album:2Dw4fYqDQnxsgoXDdMbqh3"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/0X2BH1fck6amBIoJhDVmmJ"
            },
            "href": "https://api.spotify.com/v1/artists/0X2BH1fck6amBIoJhDVmmJ",
            "id": "0X2BH1fck6amBIoJhDVmmJ",
            "name": "Ellie Goulding",
            "type": "artist",
            "uri": "spotify:artist:0X2BH1fck6amBIoJhDVmmJ"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 154435,
        "explicit": false,
        "external_ids": {
          "isrc": "GBUM71304067"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7CFQrZR4WeKEg4vweqp8Gv"
        },
        "href": "https://api.spotify.com/v1/tracks/7CFQrZR4WeKEg4vweqp8Gv",
        "id": "7CFQrZR4WeKEg4vweqp8Gv",
        "is_local": false,
        "name": "How Long Will I Love You - Bonus Track",
        "popularity": 68,
        "preview_url": null,
        "track_number": 21,
        "type": "track",
        "uri": "spotify:track:7CFQrZR4WeKEg4vweqp8Gv"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/1l8Fu6IkuTP0U5QetQJ5Xt"
              },
              "href": "https://api.spotify.com/v1/artists/1l8Fu6IkuTP0U5QetQJ5Xt",
              "id": "1l8Fu6IkuTP0U5QetQJ5Xt",
              "name": "Fifth Harmony",
              "type": "artist",
              "uri": "spotify:artist:1l8Fu6IkuTP0U5QetQJ5Xt"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0pF0oyuPNdOObniB1Ng0kW"
          },
          "href": "https://api.spotify.com/v1/albums/0pF0oyuPNdOObniB1Ng0kW",
          "id": "0pF0oyuPNdOObniB1Ng0kW",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273d03fa6f4e758282b7920b5c8",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02d03fa6f4e758282b7920b5c8",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851d03fa6f4e758282b7920b5c8",
              "width": 64
            }
          ],
          "name": "7/27 (Deluxe)",
          "release_date": "2016-05-27",
          "release_date_precision": "day",
          "total_tracks": 12,
          "type": "album",
          "uri": "spotify:album:0pF0oyuPNdOObniB1Ng0kW"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/1l8Fu6IkuTP0U5QetQJ5Xt"
            },
            "href": "https://api.spotify.com/v1/artists/1l8Fu6IkuTP0U5QetQJ5Xt",
            "id": "1l8Fu6IkuTP0U5QetQJ5Xt",
            "name": "Fifth Harmony",
            "type": "artist",
            "uri": "spotify:artist:1l8Fu6IkuTP0U5QetQJ5Xt"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6PXS4YHDkKvl1wkIl4V8DL"
            },
            "href": "https://api.spotify.com/v1/artists/6PXS4YHDkKvl1wkIl4V8DL",
            "id": "6PXS4YHDkKvl1wkIl4V8DL",
            "name": "Fetty Wap",
            "type": "artist",
            "uri": "spotify:artist:6PXS4YHDkKvl1wkIl4V8DL"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 210573,
        "explicit": false,
        "external_ids": {
          "isrc": "USSM11601121"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/7nD9nN3jord9wWcfW3Gkcm"
        },
        "href": "https://api.spotify.com/v1/tracks/7nD9nN3jord9wWcfW3Gkcm",
        "id": "7nD9nN3jord9wWcfW3Gkcm",
        "is_local": false,
        "name": "All In My Head (Flex) (feat. Fetty Wap)",
        "popularity": 65,
        "preview_url": "https://p.scdn.co/mp3-preview/c3c593d81c48111296aa5c777d8191305914845e?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 6,
        "type": "track",
        "uri": "spotify:track:7nD9nN3jord9wWcfW3Gkcm"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/7LImGq5KnzQobZciDJpeJb"
              },
              "href": "https://api.spotify.com/v1/artists/7LImGq5KnzQobZciDJpeJb",
              "id": "7LImGq5KnzQobZciDJpeJb",
              "name": "Charlotte Lawrence",
              "type": "artist",
              "uri": "spotify:artist:7LImGq5KnzQobZciDJpeJb"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CW",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GB",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IE",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/0UkABhrJ1PM3iQ1NxAxDsq"
          },
          "href": "https://api.spotify.com/v1/albums/0UkABhrJ1PM3iQ1NxAxDsq",
          "id": "0UkABhrJ1PM3iQ1NxAxDsq",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273a2bb57af533aa1ba28bb97a3",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02a2bb57af533aa1ba28bb97a3",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851a2bb57af533aa1ba28bb97a3",
              "width": 64
            }
          ],
          "name": "Charlotte",
          "release_date": "2021-03-05",
          "release_date_precision": "day",
          "total_tracks": 7,
          "type": "album",
          "uri": "spotify:album:0UkABhrJ1PM3iQ1NxAxDsq"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/7LImGq5KnzQobZciDJpeJb"
            },
            "href": "https://api.spotify.com/v1/artists/7LImGq5KnzQobZciDJpeJb",
            "id": "7LImGq5KnzQobZciDJpeJb",
            "name": "Charlotte Lawrence",
            "type": "artist",
            "uri": "spotify:artist:7LImGq5KnzQobZciDJpeJb"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CW",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GB",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IE",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 171908,
        "explicit": true,
        "external_ids": {
          "isrc": "USAT21903663"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/09rBX6mQFN1GFJgfqUQak5"
        },
        "href": "https://api.spotify.com/v1/tracks/09rBX6mQFN1GFJgfqUQak5",
        "id": "09rBX6mQFN1GFJgfqUQak5",
        "is_local": false,
        "name": "Why Do You Love Me",
        "popularity": 65,
        "preview_url": "https://p.scdn.co/mp3-preview/d7e0520dd0eb3f8f41e67b8e037135347765b48d?cid=774b29d4f13844c495f206cafdad9c86",
        "track_number": 7,
        "type": "track",
        "uri": "spotify:track:09rBX6mQFN1GFJgfqUQak5"
      },
      {
        "album": {
          "album_type": "ALBUM",
          "artists": [
            {
              "external_urls": {
                "spotify": "https://open.spotify.com/artist/6nS5roXSAGhTGr34W6n7Et"
              },
              "href": "https://api.spotify.com/v1/artists/6nS5roXSAGhTGr34W6n7Et",
              "id": "6nS5roXSAGhTGr34W6n7Et",
              "name": "Disclosure",
              "type": "artist",
              "uri": "spotify:artist:6nS5roXSAGhTGr34W6n7Et"
            }
          ],
          "available_markets": [
            "AD",
            "AE",
            "AG",
            "AL",
            "AM",
            "AO",
            "AR",
            "AT",
            "AU",
            "AZ",
            "BA",
            "BB",
            "BD",
            "BE",
            "BF",
            "BG",
            "BH",
            "BI",
            "BJ",
            "BN",
            "BO",
            "BR",
            "BS",
            "BT",
            "BW",
            "BY",
            "BZ",
            "CA",
            "CD",
            "CG",
            "CH",
            "CI",
            "CL",
            "CM",
            "CO",
            "CR",
            "CV",
            "CY",
            "CZ",
            "DE",
            "DJ",
            "DK",
            "DM",
            "DO",
            "DZ",
            "EC",
            "EE",
            "EG",
            "ES",
            "FI",
            "FJ",
            "FM",
            "FR",
            "GA",
            "GD",
            "GE",
            "GH",
            "GM",
            "GN",
            "GQ",
            "GR",
            "GT",
            "GW",
            "GY",
            "HK",
            "HN",
            "HR",
            "HT",
            "HU",
            "ID",
            "IL",
            "IN",
            "IQ",
            "IS",
            "IT",
            "JM",
            "JO",
            "JP",
            "KE",
            "KG",
            "KH",
            "KI",
            "KM",
            "KN",
            "KR",
            "KW",
            "KZ",
            "LA",
            "LB",
            "LC",
            "LI",
            "LK",
            "LR",
            "LS",
            "LT",
            "LU",
            "LV",
            "LY",
            "MA",
            "MC",
            "MD",
            "ME",
            "MG",
            "MH",
            "MK",
            "ML",
            "MN",
            "MO",
            "MR",
            "MT",
            "MU",
            "MV",
            "MW",
            "MX",
            "MY",
            "MZ",
            "NA",
            "NE",
            "NG",
            "NI",
            "NL",
            "NO",
            "NP",
            "NR",
            "NZ",
            "OM",
            "PA",
            "PE",
            "PG",
            "PH",
            "PK",
            "PL",
            "PS",
            "PT",
            "PW",
            "PY",
            "QA",
            "RO",
            "RS",
            "RU",
            "RW",
            "SA",
            "SB",
            "SC",
            "SE",
            "SG",
            "SI",
            "SK",
            "SL",
            "SM",
            "SN",
            "SR",
            "ST",
            "SV",
            "SZ",
            "TD",
            "TG",
            "TH",
            "TJ",
            "TL",
            "TN",
            "TO",
            "TR",
            "TT",
            "TV",
            "TW",
            "TZ",
            "UA",
            "UG",
            "US",
            "UY",
            "UZ",
            "VC",
            "VE",
            "VN",
            "VU",
            "WS",
            "XK",
            "ZA",
            "ZM",
            "ZW"
          ],
          "external_urls": {
            "spotify": "https://open.spotify.com/album/08ipn1MH7xqgoqhUbtvCTy"
          },
          "href": "https://api.spotify.com/v1/albums/08ipn1MH7xqgoqhUbtvCTy",
          "id": "08ipn1MH7xqgoqhUbtvCTy",
          "images": [
            {
              "height": 640,
              "url": "https://i.scdn.co/image/ab67616d0000b273e2f9df5c00476154a4fbdfff",
              "width": 640
            },
            {
              "height": 300,
              "url": "https://i.scdn.co/image/ab67616d00001e02e2f9df5c00476154a4fbdfff",
              "width": 300
            },
            {
              "height": 64,
              "url": "https://i.scdn.co/image/ab67616d00004851e2f9df5c00476154a4fbdfff",
              "width": 64
            }
          ],
          "name": "Caracal (Deluxe)",
          "release_date": "2015-09-25",
          "release_date_precision": "day",
          "total_tracks": 14,
          "type": "album",
          "uri": "spotify:album:08ipn1MH7xqgoqhUbtvCTy"
        },
        "artists": [
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/6nS5roXSAGhTGr34W6n7Et"
            },
            "href": "https://api.spotify.com/v1/artists/6nS5roXSAGhTGr34W6n7Et",
            "id": "6nS5roXSAGhTGr34W6n7Et",
            "name": "Disclosure",
            "type": "artist",
            "uri": "spotify:artist:6nS5roXSAGhTGr34W6n7Et"
          },
          {
            "external_urls": {
              "spotify": "https://open.spotify.com/artist/06nevPmNVfWUXyZkccahL8"
            },
            "href": "https://api.spotify.com/v1/artists/06nevPmNVfWUXyZkccahL8",
            "id": "06nevPmNVfWUXyZkccahL8",
            "name": "Gregory Porter",
            "type": "artist",
            "uri": "spotify:artist:06nevPmNVfWUXyZkccahL8"
          }
        ],
        "available_markets": [
          "AD",
          "AE",
          "AG",
          "AL",
          "AM",
          "AO",
          "AR",
          "AT",
          "AU",
          "AZ",
          "BA",
          "BB",
          "BD",
          "BE",
          "BF",
          "BG",
          "BH",
          "BI",
          "BJ",
          "BN",
          "BO",
          "BR",
          "BS",
          "BT",
          "BW",
          "BY",
          "BZ",
          "CA",
          "CD",
          "CG",
          "CH",
          "CI",
          "CL",
          "CM",
          "CO",
          "CR",
          "CV",
          "CY",
          "CZ",
          "DE",
          "DJ",
          "DK",
          "DM",
          "DO",
          "DZ",
          "EC",
          "EE",
          "EG",
          "ES",
          "FI",
          "FJ",
          "FM",
          "FR",
          "GA",
          "GD",
          "GE",
          "GH",
          "GM",
          "GN",
          "GQ",
          "GR",
          "GT",
          "GW",
          "GY",
          "HK",
          "HN",
          "HR",
          "HT",
          "HU",
          "ID",
          "IL",
          "IN",
          "IQ",
          "IS",
          "IT",
          "JM",
          "JO",
          "JP",
          "KE",
          "KG",
          "KH",
          "KI",
          "KM",
          "KN",
          "KR",
          "KW",
          "KZ",
          "LA",
          "LB",
          "LC",
          "LI",
          "LK",
          "LR",
          "LS",
          "LT",
          "LU",
          "LV",
          "LY",
          "MA",
          "MC",
          "MD",
          "ME",
          "MG",
          "MH",
          "MK",
          "ML",
          "MN",
          "MO",
          "MR",
          "MT",
          "MU",
          "MV",
          "MW",
          "MX",
          "MY",
          "MZ",
          "NA",
          "NE",
          "NG",
          "NI",
          "NL",
          "NO",
          "NP",
          "NR",
          "NZ",
          "OM",
          "PA",
          "PE",
          "PG",
          "PH",
          "PK",
          "PL",
          "PS",
          "PT",
          "PW",
          "PY",
          "QA",
          "RO",
          "RS",
          "RU",
          "RW",
          "SA",
          "SB",
          "SC",
          "SE",
          "SG",
          "SI",
          "SK",
          "SL",
          "SM",
          "SN",
          "SR",
          "ST",
          "SV",
          "SZ",
          "TD",
          "TG",
          "TH",
          "TJ",
          "TL",
          "TN",
          "TO",
          "TR",
          "TT",
          "TV",
          "TW",
          "TZ",
          "UA",
          "UG",
          "US",
          "UY",
          "UZ",
          "VC",
          "VE",
          "VN",
          "VU",
          "WS",
          "XK",
          "ZA",
          "ZM",
          "ZW"
        ],
        "disc_number": 1,
        "duration_ms": 315000,
        "explicit": false,
        "external_ids": {
          "isrc": "GBUM71503335"
        },
        "external_urls": {
          "spotify": "https://open.spotify.com/track/19Az4r4Tb5VKSnajMPg8hb"
        },
        "href": "https://api.spotify.com/v1/tracks/19Az4r4Tb5VKSnajMPg8hb",
        "id": "19Az4r4Tb5VKSnajMPg8hb",
        "is_local": false,
        "name": "Holding On",
        "popularity": 56,
        "preview_url": null,
        "track_number": 3,
        "type": "track",
        "uri": "spotify:track:19Az4r4Tb5VKSnajMPg8hb"
      }
    ],
    "seeds": [
      {
        "initialPoolSize": 250,
        "afterFilteringSize": 250,
        "afterRelinkingSize": 250,
        "id": "4NHQUGzhtTLFvgF5SZesLK",
        "type": "ARTIST",
        "href": "https://api.spotify.com/v1/artists/4NHQUGzhtTLFvgF5SZesLK"
      },
      {
        "initialPoolSize": 249,
        "afterFilteringSize": 249,
        "afterRelinkingSize": 249,
        "id": "0c6xIDDpzE81m2q797ordA",
        "type": "TRACK",
        "href": "https://api.spotify.com/v1/tracks/0c6xIDDpzE81m2q797ordA"
      }
    ]
  }

  export default recommendations;